/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package displaytweets;

import PiechartUI.PieChartUI;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.reflect.Array;
import java.util.ArrayList;
import twitter4j.Status;
import twitter4j.TwitterException;
import twitter4j.TwitterObjectFactory;

/**
 *
 * @author Kenan
 */
public class FilteredResultsDisplay extends javax.swing.JFrame {

    private ArrayList<File> filteredList;
    private final int pageLen; // length of pages (number of tweets in a page)
    private int pageNum; // currently displayed page
    private PieChartUI pieUI;
    /**
     * Creates new form FilteredResultsDisplay
     */
    public FilteredResultsDisplay(ArrayList<File> fList, PieChartUI pc) {
        initComponents();
        pageLen = 10;
        pageNum = 0; // first page
        pieUI = pc;
        
        setFilteredList(fList);
    }
    public FilteredResultsDisplay(ArrayList<File> fList, PieChartUI pc, int pL) {
        filteredList = fList;
        initComponents();
        // Results Variables
        pageLen = pL;
        pageNum = 0; // first page
        pieUI = pc;
        
        setFilteredList(fList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultsScrollPane = new javax.swing.JScrollPane();
        resultPane = new javax.swing.JPanel();
        previousButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        pageSelect = new javax.swing.JComboBox<>();
        nextButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tweetPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        previousButton.setText("Previous Page");
        previousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousButtonMouseClicked(evt);
            }
        });

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next Page");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });

        tweetPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tweetPanel.setLayout(new javax.swing.BoxLayout(tweetPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(tweetPanel);

        javax.swing.GroupLayout resultPaneLayout = new javax.swing.GroupLayout(resultPane);
        resultPane.setLayout(resultPaneLayout);
        resultPaneLayout.setHorizontalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(resultPaneLayout.createSequentialGroup()
                        .addComponent(previousButton)
                        .addGap(18, 18, 18)
                        .addComponent(pageSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goButton)
                        .addGap(145, 145, 145)
                        .addComponent(nextButton))
                    .addComponent(jScrollPane2))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        resultPaneLayout.setVerticalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButton)
                    .addComponent(goButton)
                    .addComponent(pageSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton))
                .addContainerGap())
        );

        resultsScrollPane.setViewportView(resultPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseClicked
        if (pageNum > 0) {
            pageNum--;
            UpdateFilterDisplay();
        }
    }//GEN-LAST:event_previousButtonMouseClicked

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        pageNum = pageSelect.getSelectedIndex();
        UpdateFilterDisplay();
    }//GEN-LAST:event_goButtonActionPerformed

    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        if ((pageNum+1) * pageLen < filteredList.size()) {
            pageNum++;
            UpdateFilterDisplay();
        }
    }//GEN-LAST:event_nextButtonMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (pieUI.negFrame == this)
            pieUI.negFrame = null;
    }//GEN-LAST:event_formWindowClosed

    // Set the list of filtered tweet files and update the display to show them
    private void setFilteredList(ArrayList<File> tweets) {
        // Set the tweet files to show
        filteredList = tweets;
        // Set the page dropdown to number of pages
        String[] pages = new String[(int)Math.ceil((double)filteredList.size()/pageLen)];
        for (int i = 0; i < Array.getLength(pages); i++) {
            pages[i] = Integer.toString(i+1);
        }
        pageSelect.setModel(new javax.swing.DefaultComboBoxModel<>(pages));
        
        UpdateFilterDisplay();
    }
    // Display the tweets for the current page
    private void UpdateFilterDisplay() {
        // clear panel of previous page (if applicable)
        tweetPanel.removeAll();
        pageSelect.setSelectedIndex(pageNum);
        try {
        // Iterate through the files, displaying the tweets
            for (int i = pageLen * pageNum; i < Integer.min((pageNum+1)*pageLen, filteredList.size());i++) {
                // Create Status Object from the file and add to panel
                String rawJSON = readFirstLine(filteredList.get(i));
                TweetStatus stat = new TweetStatus(rawJSON);
                tweetPanel.add(stat);
            }
            // make changes visible
            tweetPanel.revalidate();
          // Exceptions if errors in getting tweets
        } catch (IOException ioe) {
            System.out.println("Failed to store tweets: " + ioe.getMessage());
        }
    }
    
    // method to retrieve the tweets from the files (UTF-8 format)
    // Copyright 2007 Yusuke Yamamoto
    private static String readFirstLine(File fileName) throws IOException {
        FileInputStream fis = null;
        InputStreamReader isr = null;
        BufferedReader br = null;
        try {
            fis = new FileInputStream(fileName);
            isr = new InputStreamReader(fis, "UTF-8");
            br = new BufferedReader(isr);
            return br.readLine();
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException ignore) {
                }
            }
            if (isr != null) {
                try {
                    isr.close();
                } catch (IOException ignore) {
                }
            }
            if (fis != null) {
                try {
                    fis.close();
                } catch (IOException ignore) {
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox<String> pageSelect;
    private javax.swing.JButton previousButton;
    private javax.swing.JPanel resultPane;
    private javax.swing.JScrollPane resultsScrollPane;
    private javax.swing.JPanel tweetPanel;
    // End of variables declaration//GEN-END:variables
}
