/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package displaytweets;

/**
 *
 * @author Kenan
 */
public class TweetStatus extends javax.swing.JPanel {

    /**
     * Creates new form tweetstatus
     * @param uname
     * @param screenName
     * @param tweetText
     */
    public TweetStatus(String uname, String screenName, String tweetText) {
        initComponents();
        fillInTweet(uname, screenName, tweetText);
    }

    // Fills in the Tweet form with the tweet information 
    private void fillInTweet(String uname, String screenName, String tweetText) {
        username.setText(uname);
        screenname.setText("@" + screenName);
        StatusText.setText(tweetText);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StatusText = new javax.swing.JTextArea();
        profile = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        screenname = new javax.swing.JLabel();
        twicon = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        Location = new javax.swing.JLabel();
        retweet = new javax.swing.JLabel();
        profile_r = new javax.swing.JLabel();
        username_r = new javax.swing.JLabel();
        screenname_r = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        StatusText.setEditable(false);
        StatusText.setColumns(20);
        StatusText.setLineWrap(true);
        StatusText.setRows(5);
        StatusText.setBorder(null);
        jScrollPane1.setViewportView(StatusText);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/displaytweets/twitter_logo.png"))); // NOI18N

        username.setText("user");

        screenname.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        screenname.setText("screen");

        twicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/displaytweets/twitter_logo.png"))); // NOI18N
        twicon.setMaximumSize(new java.awt.Dimension(60, 60));
        twicon.setMinimumSize(new java.awt.Dimension(45, 45));
        twicon.setPreferredSize(new java.awt.Dimension(52, 52));

        date.setText("date");

        Location.setText("Location");

        retweet.setEnabled(false);

        profile_r.setIcon(new javax.swing.ImageIcon(getClass().getResource("/displaytweets/twitter_logo.png"))); // NOI18N
        profile_r.setEnabled(false);

        username_r.setText("user");
        username_r.setEnabled(false);

        screenname_r.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        screenname_r.setText("screen");
        screenname_r.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Location))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(profile)
                                .addComponent(profile_r))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(screenname)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(username)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(retweet)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(twicon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(username_r)
                                .addComponent(screenname_r)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profile)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(username)
                                .addComponent(retweet))
                            .addComponent(twicon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(screenname)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_r)
                    .addComponent(profile_r))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(screenname_r)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(Location))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel Location;
    javax.swing.JTextArea StatusText;
    javax.swing.JLabel date;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JLabel profile;
    javax.swing.JLabel profile_r;
    javax.swing.JLabel retweet;
    javax.swing.JLabel screenname;
    javax.swing.JLabel screenname_r;
    javax.swing.JLabel twicon;
    javax.swing.JLabel username;
    javax.swing.JLabel username_r;
    // End of variables declaration//GEN-END:variables
}
